/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MiniPCController;
import Model.CPU;
import Model.FileManager;
import Model.Memory;
import Model.MemoryRegister;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author aleja
 */
public class MiniPCMenu extends javax.swing.JFrame {
    
    public MiniPCController controller = new MiniPCController();
    public FileManager fileManager = new FileManager();
    int rowCount = 0;
    int currentAddress = 0;
    
    /**
     * Creates new form NewJFrame
     */
    public MiniPCMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextInstructionBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        loadFileBtn = new javax.swing.JButton();
        nextInstructionBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblAX = new javax.swing.JLabel();
        lblNumberAX = new javax.swing.JLabel();
        lblBX = new javax.swing.JLabel();
        lblCX = new javax.swing.JLabel();
        lblDX = new javax.swing.JLabel();
        lblNumberBX = new javax.swing.JLabel();
        lblNumberCX = new javax.swing.JLabel();
        lblNumberDX = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        lblNumberPC = new javax.swing.JLabel();
        lblNumberAC = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblIR = new javax.swing.JLabel();
        lblNumberIR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCode = new javax.swing.JTable();
        lblRegistros = new javax.swing.JLabel();
        nextInstructionBtn3 = new javax.swing.JButton();
        nextInstructionBtn4 = new javax.swing.JButton();

        nextInstructionBtn1.setText("Siguiente instrucción");
        nextInstructionBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadFileBtn.setText("Cargar archivo ");
        loadFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileBtnActionPerformed(evt);
            }
        });

        nextInstructionBtn.setText("Siguiente instrucción");
        nextInstructionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtnActionPerformed(evt);
            }
        });

        lblAX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblAX.setText("AX:");

        lblNumberAX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberAX.setText("0");

        lblBX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblBX.setText("BX:");

        lblCX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCX.setText("CX:");

        lblDX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDX.setText("DX:");

        lblNumberBX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberBX.setText("0");

        lblNumberCX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberCX.setText("0");

        lblNumberDX.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberDX.setText("0");

        lblPC.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPC.setText("PC:");

        lblNumberPC.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberPC.setText("0");

        lblNumberAC.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberAC.setText("0");

        lblAC.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblAC.setText("AC:");

        lblIR.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIR.setText("IR:");

        lblNumberIR.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumberIR.setText("0");

        tblCode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo ASM", "Codigo binario", "Address"
            }
        ));
        tblCode.setRowHeight(30);
        jScrollPane1.setViewportView(tblCode);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAX)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumberAX))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBX)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumberBX)))
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDX)
                    .addComponent(lblCX))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberCX)
                    .addComponent(lblNumberDX))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAC)
                    .addComponent(lblPC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNumberPC)
                        .addGap(51, 51, 51)
                        .addComponent(lblIR)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumberIR))
                    .addComponent(lblNumberAC))
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAX)
                            .addComponent(lblNumberAX)
                            .addComponent(lblCX)
                            .addComponent(lblNumberCX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBX)
                            .addComponent(lblNumberBX)
                            .addComponent(lblDX)
                            .addComponent(lblNumberDX)
                            .addComponent(lblAC)
                            .addComponent(lblNumberAC))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPC)
                            .addComponent(lblNumberPC)
                            .addComponent(lblIR)
                            .addComponent(lblNumberIR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );

        lblRegistros.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRegistros.setText("Registros");

        nextInstructionBtn3.setText("Salir");
        nextInstructionBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtn3ActionPerformed(evt);
            }
        });

        nextInstructionBtn4.setText("Limpiar");
        nextInstructionBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(loadFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextInstructionBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nextInstructionBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextInstructionBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadFileBtn)
                    .addComponent(nextInstructionBtn)
                    .addComponent(nextInstructionBtn4)
                    .addComponent(nextInstructionBtn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileBtnActionPerformed
        if (evt.getSource() == loadFileBtn) {
            String filePath = fileManager.selectFile(this);
            fileManager.loadOperations();
            fileManager.loadDataRegisters();
            ArrayList<MemoryRegister> instructionSet = fileManager.loadFileInstructions(filePath);
            System.out.println(instructionSet);
            
            Memory memory = new Memory(instructionSet.size());
            memory.allocateMemory(instructionSet);
            CPU cpu = new CPU(memory);
            this.getController().setCpu(cpu);
            this.setCurrentAddress(this.controller.getCpu().getMemory().getAllocationStartIndex());
            System.out.println(cpu);
            
            this.updateTable(this.fileManager.getInstructions(),this.getRowCount(), this.getCurrentAddress());
        }
    }//GEN-LAST:event_loadFileBtnActionPerformed

    private void updateTable(ArrayList<MemoryRegister> instructionSet, int row, int addressIndex) {                                            
        this.getTblCode().setValueAt(instructionSet.get(row).getAsmInstructionString(), row, 0);
        this.getTblCode().setValueAt(instructionSet.get(row).convertToBinary(), row, 1);
        this.getTblCode().setValueAt(this.getCurrentAddress(), row, 2);
        this.setRowCount(this.getRowCount()+1);
        this.setCurrentAddress(this.getCurrentAddress()+1);
    } 

    public MiniPCController getController() {
        return controller;
    }

    public void setController(MiniPCController controller) {
        this.controller = controller;
    }

    public int getCurrentAddress() {
        return currentAddress;
    }

    public void setCurrentAddress(int currentAddress) {
        this.currentAddress = currentAddress;
    }

    
    
    public int getRowCount() {
        return rowCount;
    }

    public void setRowCount(int rowCount) {
        this.rowCount = rowCount;
    }
    
    
    
    public JTable getTblCode() {
        return tblCode;
    }

    public void setTblCode(JTable tblCode) {
        this.tblCode = tblCode;
    }

    
    
    public JLabel getLblNumberAC() {
        return lblNumberAC;
    }

    public void setLblNumberAC(JLabel lblNumberAC) {
        this.lblNumberAC = lblNumberAC;
    }

    public JLabel getLblNumberAX() {
        return lblNumberAX;
    }

    public void setLblNumberAX(JLabel lblNumberAX) {
        this.lblNumberAX = lblNumberAX;
    }

    public JLabel getLblNumberBX() {
        return lblNumberBX;
    }

    public void setLblNumberBX(JLabel lblNumberBX) {
        this.lblNumberBX = lblNumberBX;
    }

    public JLabel getLblNumberCX() {
        return lblNumberCX;
    }

    public void setLblNumberCX(JLabel lblNumberCX) {
        this.lblNumberCX = lblNumberCX;
    }

    public JLabel getLblNumberDX() {
        return lblNumberDX;
    }

    public void setLblNumberDX(JLabel lblNumberDX) {
        this.lblNumberDX = lblNumberDX;
    }

    public JLabel getLblNumberIR() {
        return lblNumberIR;
    }

    public void setLblNumberIR(JLabel lblNumberIR) {
        this.lblNumberIR = lblNumberIR;
    }

    public JLabel getLblNumberPC() {
        return lblNumberPC;
    }

    public void setLblNumberPC(JLabel lblNumberPC) {
        this.lblNumberPC = lblNumberPC;
    }

    public FileManager getFileManager() {
        return fileManager;
    }

    public void setFileManager(FileManager fileManager) {
        this.fileManager = fileManager;
    }

    
    
    private void nextInstructionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtnActionPerformed
        this.updateTable(this.fileManager.getInstructions(), this.getRowCount(), this.getCurrentAddress());
    }//GEN-LAST:event_nextInstructionBtnActionPerformed

    private void nextInstructionBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextInstructionBtn1ActionPerformed

    private void nextInstructionBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextInstructionBtn3ActionPerformed

    private void nextInstructionBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextInstructionBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniPCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniPCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniPCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniPCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniPCMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblAX;
    private javax.swing.JLabel lblBX;
    private javax.swing.JLabel lblCX;
    private javax.swing.JLabel lblDX;
    private javax.swing.JLabel lblIR;
    private javax.swing.JLabel lblNumberAC;
    private javax.swing.JLabel lblNumberAX;
    private javax.swing.JLabel lblNumberBX;
    private javax.swing.JLabel lblNumberCX;
    private javax.swing.JLabel lblNumberDX;
    private javax.swing.JLabel lblNumberIR;
    private javax.swing.JLabel lblNumberPC;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JButton loadFileBtn;
    private javax.swing.JButton nextInstructionBtn;
    private javax.swing.JButton nextInstructionBtn1;
    private javax.swing.JButton nextInstructionBtn3;
    private javax.swing.JButton nextInstructionBtn4;
    private javax.swing.JTable tblCode;
    // End of variables declaration//GEN-END:variables
}
